MazeSize:
  measure: progress
  thresholds: [0.1, 0.3, 0.5, 0.7]
  min_lesson_length: 100
  signal_smoothing: true
  parameters:
    mazeSize_x: [3, 5, 7, 9, 11, 13]
    mazeSize_y: [3, 5, 7, 9, 11, 13]